# Compiler
CXX=g++

# Target executable name
TARGET=ex3.out

# Source files
SRC=main.cpp

# Compiler flags
CXXFLAGS=-std=c++20

# Build target
$(TARGET): $(SRC)
	$(CXX) $(CXXFLAGS) -o $(TARGET) $(SRC)

# Clean compiled files
clean:
	rm -f $(TARGET)
